name: Docker build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  jpo-security-svcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: ls -la && pwd 
      - name: Build
        run: |
          build_service() {
            local service_dir=$1
            echo "Building Docker image for ${service_dir}..."
            cd ${service_dir}
            docker buildx build .
            cd - > /dev/null
          }
          
          build_service "security-svc"
          build_service "ext-signature-svc-mock"