name: Docker build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  jpo-security-svcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: ls -la && cd security-svc && pwd 
      - name: Build
        uses: docker/build-push-action@v5